### ISSUE TITLE
create dropdown list for eligible securities to select

### ISSUE THREAD

**Issue by eervin123** [Cyrusb01/Streamlit-bt#2]
Rather than let the user type in a random input text string, start with a list of eligible securities to select from.

For starters, create a list of `spy,efa,iwm,vwo,ibb,agg,hyg,gld,slv,tsla,aapl,msft,qqq,btc-usd,eth-usd` later you can create a dictionary of symbol and name so the person could know what they were selecting even if they didn't know the ticker, but this is good for now.

Later, we can import a list of all the available tickers on the stock exchange, and you can just confirm that the user input is within the list but that's for another time.  For now, I really just care about spy, agg, and btc-usd

**Comment by Cyrusb01** [comment]
Have implemented the drop down with  the tickers you gave
